### ISSUE TITLE
compiler error on sp_utils lib

### ISSUE THREAD

**Issue by Xis-Ytneves** [CasperTheCat/D3D11Wrapper#1]
I can compile the debug version without error, but when I try to compile the release version I get the error C1047: The object or library file 'lib\sp_utils_x64.lib' was created with an older compiler than other objects. I'm using the lib you posted in the prior issue. Have you got an update by chance?

**Comment by CasperTheCat** [comment]
I don't recognise that library, and the project compiles for me in VS15 and VS16. May I ask what compiler version you are using?

Also, the Dev and Split branches won't compile as they are both missing a header due to licensing concerns. I'll port the maths over to GLM at some point, but it has been a while since I worked with Windows.

**Comment by Xis-Ytneves** [comment]
I was being stupid ... sorry!
